### ISSUE TITLE
Minor bugs and suggestions

### ISSUE THREAD

**Issue by GuptaAyush19** [j0eTheRipper/function-analisis#1]
In _main.py_, please change the string variable _menu_ option 3 to "ax + by = c" from "ax+bx=c". You can even add a _README.md_ to your GitHub repository so that users can understand the code better. Lastly, error handling in _main.py_ will be great addition, so that whenever a user inputs a wrong format into the program, it won't break the loop and give one more chance to the user. 
I had made a similar program to calculate the roots of a quadratic equation, tell me if you are interested?? Meanwhile please check my GitHub repositories and give suggestions or make new branches. Either will be helpful.
PS - I came to know of this project via Reddit (r/Python).
@j0eTheRipper

**Comment by j0eTheRipper** [comment]
Thanks for your suggestions. These are definitely going to be help full.
